# Generated by Django 4.0.4 on 2022-05-28 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default="D:\x01Mentor\\Altair\\CEID\\Εξεταστική 2021-2022\\Β' Εξάμηνο\\Τεχνολογία Λογισμικού\\Project\\Pawsome\\pawsome\\Pawsome\\Images\\logo_transparent.png", max_length=255, null=True, upload_to="D:\x01Mentor\\Altair\\CEID\\Εξεταστική 2021-2022\\Β' Εξάμηνο\\Τεχνολογία Λογισμικού\\Project\\Pawsome\\pawsome\\Pawsome\\Images")),
                ('confirm_password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('org', 'Organizations'), ('pros', 'Professional'), ('pet-owner', 'Pet Owner')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('AFM', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('hours', models.TimeField()),
                ('telephone', models.CharField(max_length=12)),
                ('certificate', models.FileField(upload_to='')),
                ('CV', models.FileField(upload_to='')),
                ('license', models.FileField(upload_to='')),
                ('prof_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('Users.users',),
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pet_name', models.CharField(max_length=50)),
                ('owner_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('Users.users',),
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('AFM', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('hours', models.TimeField()),
                ('telephone', models.CharField(max_length=12)),
                ('org_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('Users.users',),
        ),
    ]
